CREATE DATABASE nuvix;
USE nuvix;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    senha VARCHAR(255) NOT NULL,
    dataCriacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
